function [fitresult, gof] = createFit(x3, y3)
%CREATEFIT(X3,Y3)
%  Create a fit.
%
%  Data for 'Ratio of Eccentricity' fit:
%      X Input: x3
%      Y Output: y3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2024 03:14:16


%% Fit: 'Ratio of Eccentricity'.
[xData, yData] = prepareCurveData( x3, y3 );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [43.1875474722831 -0.382348801190141];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Ratio of Eccentricity' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'y3 vs. x3', 'Ratio of Eccentricity', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x3', 'Interpreter', 'none' );
ylabel( 'y3', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'Ratio of Eccentricity - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x3', 'Interpreter', 'none' );
ylabel( 'y3', 'Interpreter', 'none' );
grid on


